### ISSUE TITLE
doesn't handle todos prefaced by semicolon

### ISSUE THREAD

**Issue by masukomi** [augmentable-dev/tickgit#27]
Lisps use `;` to indicate the start of a single line comment

This file, saved as `todotest.scm` 

```
; TODO: test scheme comments
(print "hello") ; TODO: after code
```

results in NO todos

**Comment by patrickdevivo** [comment]
Thanks for pointing this out! We use [enry](https://github.com/src-d/enry) to infer the language of a  file and apply different comment parsing: https://github.com/augmentable-dev/tickgit/blob/master/pkg/comments/comments.go#L44

Support for Lisp style comments should be easy to add
