### ISSUE TITLE
support other "TODO" esque phrases

### ISSUE THREAD

**Issue by travisirby** [augmentable-dev/tickgit#35]
It could be a good idea to not only pull out TODO's but other phrases that codebases use.

FIXME seems to be popular. Not sure what others people commonly use

**Comment by rcoreilly** [comment]
looks like I tend to use todo: (lowercase, colon).   maybe also without colon but with space sometimes.

**Comment by patrickdevivo** [comment]
The linked PR#44 should address this in a fairly basic way (it gets the job done and leaves a couple of TODOs for improvement in later iterations 🙂)

@rcoreilly thanks for the suggestion of `todo`! though I'm a bit worried about potential false positives matching with the "naked" lower case version (without an `@` preceding it).

Maybe it's an unnecessary concern (I don't think there are many code comments out there with the word `mastodon` in them 🙂), but there might be a fair number of codebases that invoke `todo` in a comment (I'm thinking about all those front-end To-Do list apps) to refer to a variable or type, and not as an indicator.

in my mind, an `ALLCAPS` phrase or one preceded by a symbol such as `@` is a stronger indicator of a "marker" of something to return to, and so I'm more comfortable matching against it.

Eventually, having user supplied phrases would be ideal here (also maybe word based matching not just `string.Contains(...)`

**Comment by patrickdevivo** [comment]
https://www.thefreedictionary.com/words-containing-todo

**Comment by rcoreilly** [comment]
I haven't looked at the PR but if you use a parsing strategy that first isolates "words" as anything with space or punctuation surrounding it, then that should make everything a lot more robust -- won't get any words-containing-todo in this case.

**Comment by patrickdevivo** [comment]
> I haven't looked at the PR but if you use a parsing strategy that first isolates "words" as anything with space or punctuation surrounding it, then that should make everything a lot more robust -- won't get any words-containing-todo in this case.

@rcoreilly 

Yes, you're right - and that's how it should be implemented (though not currently). The main hiccup for me was the punctuation as you mention, as I've seen `(TODO)`, `TODO:`, `TODO-` etc and I'd want to make sure to capture those as well if it's word-based parsing. I will make a note of that and implement in a future iteration!
