### ISSUE TITLE
Document installation w/o brew

### ISSUE THREAD

**Issue by clemisch** [augmentable-dev/tickgit#39]
TODO: Document the installation (or build from source) for Linux/Windows in README.

**Comment by patrickdevivo** [comment]
@clemisch I apologize I never answered this and that it's been so long! I think PR #54 partially addresses your ask here with some additional instructions on how to install the CLI binary using two non-homebrew methods, a shell script hosted by GoBinaries.com which should work on Linux, and a `go install` example for users with the go toolchain available.

Unfortunately, I haven't been able to test this project on Windows in any way and am unclear off the bat if the dependencies will work. I'll have to do some experimenting!

Please let me know if this is helpful for what you were looking for (I know it's been 6+ months)

**Comment by clemisch** [comment]
Hey, thank you for getting back on this. 

Looking at your instructions to install from source, I guess it turns out I just lack the go knowledge to setup the build environment. When I opened this issue, I thought there were some missing information, but probably it's my fault.

FWIW, from 

```bash
$ go install github.com/augmentable-dev/tickgit/cmd/tickgit
```

I get 

```
can't load package: package github.com/augmentable-dev/tickgit/cmd/tickgit: cannot find package "github.com/augmentable-dev/tickgit/cmd/tickgit" in any of:
	/usr/lib/go-1.10/src/github.com/augmentable-dev/tickgit/cmd/tickgit (from $GOROOT)
	/home/clemisch/go/src/github.com/augmentable-dev/tickgit/cmd/tickgit (from $GOPATH)
```

I assume this is because of my faulty go environment? `$GOBIN` is `/home/clemisch/go/bin`.

**Comment by chripo** [comment]
check and set your `$GOPATH` and

```sh
$ go get github.com/augmentable-dev/tickgit/...
```

**Comment by clemisch** [comment]
Thank you. `GOPATH` is `/home/clemisch/go` and from 

```
~ $ go get github.com/augmentable-dev/tickgit/...
```

I get

```
package github.com/hashicorp/hcl/v2/gohcl: cannot find package "github.com/hashicorp/hcl/v2/gohcl" in any of:
	/usr/lib/go-1.10/src/github.com/hashicorp/hcl/v2/gohcl (from $GOROOT)
	/home/clemisch/go/src/github.com/hashicorp/hcl/v2/gohcl (from $GOPATH)
package github.com/hashicorp/hcl/v2/hclparse: cannot find package "github.com/hashicorp/hcl/v2/hclparse" in any of:
	/usr/lib/go-1.10/src/github.com/hashicorp/hcl/v2/hclparse (from $GOROOT)
	/home/clemisch/go/src/github.com/hashicorp/hcl/v2/hclparse (from $GOPATH)
```

**Comment by chripo** [comment]
try to update your go version or install via

https://github.com/augmentable-dev/tickgit/pull/54/commits/dd591ee018bf52302c3f7d6ee7644b27a77f0739#diff-04c6e90faac2675aa89e2176d2eec7d8R63

**Comment by clemisch** [comment]
Thank you for the swift reply. I deleted everything in `/home/clemisch/go/src/` and 

```
~ $ go get github.com/augmentable-dev/tickgit/...
```

ran successfully. Now 

```
~ $ go install github.com/augmentable-dev/tickgit/cmd/tickgit
```

gives 

```
go/src/github.com/augmentable-dev/tickgit/pkg/comments/comments.go:13:2: code in directory /home/clemisch/go/src/github.com/go-enry/go-enry expects import "github.com/go-enry/go-enry/v2"
```

Am I missing some fundamental knowledge about go's build pipeline?

**Comment by chripo** [comment]
`go install = build + install` it requires local source
`go get = download + build + install`

**Comment by clemisch** [comment]
I don't know if I understand you correctly, but 

```
$ go get github.com/augmentable-dev/tickgit/...
```

already gives the error and the binary is not created.

**Comment by chripo** [comment]
your go version seems to be dated.
you can always start with a empty `GOPATH`.
`GOPATH=/tmp/foo go get ...`
if this works, your default `GOPATH` needs a cleanup `rm -rf  $GOPATH/src/github.com/<USR>/<REPO>` at least.

**Comment by clemisch** [comment]
> your go version seems to be dated.

You are right. I must have messed up while updating go before: I still was on 1.10 for my previous comments but now with 1.14 the command

```
$ go get github.com/augmentable-dev/tickgit/...
```

worked. Sorry for the fuss.

---

I guess this kind of resolves this issue: I was under the impression there was a fundamental problem with building from source, but it was just my setup.
