### ISSUE TITLE
Support Kotlin projects

### ISSUE THREAD

**Issue by sschuberth** [augmentable-dev/tickgit#45]
Are files being searched for TODOs somehow filtered by language / file extension? Because in [our project written in Kotlin](https://www.tickgit.com/browse?repo=github.com/oss-review-toolkit/ort) I miss a lot of TODOs from the code base.

**Comment by patrickdevivo** [comment]
Hi @sschuberth thanks for opening up an issue! Currently, `tickgit` relies on [this library](https://github.com/src-d/enry) to do language detection. It then applies rules defined [here](https://github.com/augmentable-dev/tickgit/blob/master/pkg/comments/languages.go#L43) to know how to "pluck" out comments in specific languages (and search them for TODO comments, etc). It looks like [Kotlin is "recognizable"](https://github.com/src-d/enry/blob/master/data/alias.go#L355), but `tickgit` doesn't yet know how to parse Kotlin comments. I should be able to add support fairly easily, and will open a PR to do so soon.

That being said, I've been working (on a local branch) to update `tickgit` with a newer comment parsing/identifying strategy leveraging a syntax highlighting package that should have "out of the box" support for [a lot of languages](https://github.com/alecthomas/chroma#supported-languages) without having to maintain an independent list within the `tickgit` source.

I will reference this issue when the PR is created, so you should be notified!

**Comment by patrickdevivo** [comment]
@sschuberth please see https://www.tickgit.com/browse?repo=github.com/oss-review-toolkit/ort, does that look better? If you're interested, feel free to [add a badge](https://github.com/augmentable-dev/tickgit/blob/master/docs/API.md)!

**Comment by sschuberth** [comment]
Thanks for the background info and fast fix!

> If you're interested, feel free to [add a badge](https://github.com/augmentable-dev/tickgit/blob/master/docs/API.md)!

Done: https://github.com/oss-review-toolkit/ort/pull/2576 😀
