### ISSUE TITLE
cmd

### ISSUE THREAD

**Issue by damianoneill** [augmentable-dev/tickgit#49]
Would it be possible to refactor the main.go into a folder as follows;

go get -u github.com/augmentable-dev/tickgit/cmd/tickgit 

So that the binary would be tickgit instead of cmd? 

Thanks,
Damian.

**Comment by damianoneill** [comment]
@patrickdevivo sorry I wasn't clear.  The change should be to introduce a new folder.  It should be 

github.com/augmentable-dev/tickgit/cmd/tickgit/main.go 

The the pull will be 

go get -u github.com/augmentable-dev/tickgit/cmd/tickgit

**Comment by patrickdevivo** [comment]
@damianoneill ah I understand! That seems to be inline with what we probably _should_ be doing anyways: https://github.com/golang-standards/project-layout/tree/master/cmd

PR #52 should address properly?

**Comment by damianoneill** [comment]
@patrickdevivo all good. 

```console
$ go get -u github.com/augmentable-dev/tickgit/cmd/tickgit
✔ ~
01:07 $ tickgit --help
Scans a given git repository looking for any code comments with TODOs. Displays a report of all the TODO items found.

Usage:
  todos [flags]

Flags:
      --csv-output   specify whether or not output should be in CSV format
  -h, --help         help for todos
✔ ~
```

Thanks.
